### ISSUE TITLE
Compilation error regarding "project_cxx_library_header_default"

### ISSUE THREAD

**Issue by tomvanbraeckel** [vilkov/libxdg#1]
I'm trying to compile on Ubuntu Utopic and get the following error:

Unknown CMake command "project_cxx_library_header_default".

Can you reproduce this? Any idea? I don't see the define of that symbol anywhere in the GIT clone sourcecode...

Full output:

tom@pluto:~/sources/libxdg/debug$ cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE:STRING=Release -D CMAKE_INSTALL_PREFIX:STRING=/home/tom ../
CMake Error at CMakeLists.txt:4 (project_cxx_library_header_default):
  Unknown CMake command "project_cxx_library_header_default".

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

```
cmake_minimum_required(VERSION 2.8)
```

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/tom/sources/libxdg/CMakeFiles/CMakeOutput.log".

**Comment by ManuelSchneid3r** [comment]
:+1:

**Comment by vilkov** [comment]
Fixed. Thank you for information.
